<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Yamazaki</title>
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="template/HomeImg.css">
  </head>
  <body>
    <header>
      <h1>This is team Alpha home page </h1>
      <h2> search for a movie </h2>
    </header>
    <footer>
      &copy; TeamAlpha 2019
    </footer>

  </body>
</html>
