<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Yamazaki</title>
    <!--link rel="stylesheet" href="template/master.css"-->
    <link rel="stylesheet" href="template/HomeImg.css">
  </head>
  <body>
    <header>
      <h1>This is team Alpha home page </h1>
      <h2> search for a movie </h2>
    </header>
    <footer>
      &copy; TeamAlpha 2019
    </footer>

  </body>
</html>
