<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Yamazaki</title>
    <link rel="stylesheet" href="css/master.css">
    <link rel="stylesheet" href="css/specials.css">
  </head>
  <body>
    <header>
      <h1>
        Yamazaki
      </h1>
      <h2>
        Sushi & Hibachi
      </h2>
    </header>
    <nav>
      <ul>
        <li><a href="Home.html">Home</a></li>
        <li><a href="Menu.html">Menu</a></li>
        <li><a href="Catering.html">Catering</a></li>
        <li><a href="Specials.html">Specials</a></li>
        <li><a href="Feedback.html">FeedBack</a></li>
    <!--    <li><a href="Carears.html">Carears</a></li> -->
      </ul>
    </nav>
  <!--  <h1 id="UnderConst">
      Under Constrution
    </h1> -->
    <table>
      <caption>All discounts used before tax!</caption>
      <tr>
        <th colspan="3">$5 OFF</th>
      </tr><tr>
        <td class="offers">Any purchase of $40 or more <br> dinner only </td>
        <td> OR </td>
        <td class="offers">Any purchase of $30 or more <br> dinner only, Cash Only </td>
      </tr><tr>
        <td colspan="3"> Cannot be combibined with any other offers</td>
      </tr>
    </table>
    <table>
      <tr>
        <th colspan="3">$15 OFF</th>
      </tr><tr>
        <td class="offers">Any purchase of $80 or more <br> dinner only </td>
        <td> OR </td>
        <td class="offers">Any purchase of $70 or more <br> dinner only, Cash Only </td>
      </tr><tr>
        <td colspan="3"> Cannot be combibined with any other offers</td>
      </tr>
    </table>
    <table>
      <tr>
        <th colspan="3">$25 OFF</th>
      </tr><tr>
        <td class="offers">Any purchase of $130 or more <br> dinner only </td>
        <td> OR </td>
        <td class="offers">Any purchase of $120 or more <br> dinner only, Cash Only </td>
      </tr><tr>
        <td colspan="3"> Cannot be combibined with any other offers</td>
      </tr>
    </table>
    <footer>
    </footer>
  </body>
</html>
